#!/usr/bin/env bash

bpaths=(
    "" \
    "" \
    "" \
    "" \
)

abspath() {
  # $1 : relative filename
  if [ -d "${1%/*}" ]; then
    echo "$(cd ${1%/*}; pwd)/${1##*/}"
  fi
}

drive=$(abspath ./drive/)

for b in ${bpaths[@]}; do
  dpath=$(abspath "${drive}/${b}")
  mkdir -p "${drive}"
  cp -i -R "${dpath}"
done
